---
title: "Final Project"
author: "Félix Báez-Santiago, Valeria Castañeda-Saucedo, Xinyu Lin and Angelina Lu"
date: "2025-09-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, include=FALSE}
library(haven)
library(dplyr)
library(sjlabelled)
library(sjPlot)
library(expss)
library(googledrive)
library(readr)
library(stringr)
library(tidyr)
library(poLCA)

# Authenticate with google account once
drive_auth()
```

# Read in the cogimp0 dataset

```{r}
# Access and read the cogimp0 file from the drive
cogimp0 = drive_download(
  as_id("1xDBY_8-djIWfKWTBKrxlYbZ9mkw6zlJ2"),
  path = tempfile(fileext = ".sav"),
  overwrite = TRUE
) %>%
  { read_sav(.$local_path) }  

# generate codebook dataframe
cogimp0_codebook = labelled::generate_dictionary(cogimp0)
```

# Read in the 2022 tracker file dataset

```{r}
# read in the trk2022v2 file
trk2022v2 = drive_download(
  as_id("1G0wZriMuTMftZYP834aJG7nMrN3k4T5E"),
  path = tempfile(fileext = ".sav"),
  overwrite = TRUE
) %>%
  { read_sav(.$local_path) }  

# generate codebook
trk2022v2_codebook = labelled::generate_dictionary(trk2022v2)
```

# Combine the data and variables we need

```{r}
cogimp0   <- cogimp0 %>% mutate(hhid = as.character(HHID), pn = as.character(PN))
trk2022v2 <- trk2022v2 %>% mutate(hhid = as.character(hhid), pn = as.character(pn))
```

```{r}
data_w13 <- cogimp0 %>%
  dplyr::select(hhid, pn,R13MO, R13DY, R13YR, R13DW, R13SCIS, R13CACT, R13PRES, R13VP) %>%rename(
    Month= R13MO,
    Day= R13DY,
    Year= R13YR,
    DOW= R13DW,
    Scissors= R13SCIS,
    Cactus= R13CACT,
    President= R13PRES,
    VP = R13VP
  ) %>%
  mutate(wave = "W13")
```

```{r}
cov_w13 <- trk2022v2 %>%
  dplyr::select(hhid, pn, page, gender, degree, race) %>%
  rename(age = page) %>%
  mutate(wave = "W13")
```

```{r}
lca_raw <- data_w13 %>%
  inner_join(cov_w13, by = c("hhid", "pn", "wave"))

indicator_names <- c("Month","Day","Year","DOW","Scissors","Cactus","President","VP")
```

```{r}
lca_ready <- lca_raw %>%
  dplyr::mutate(across(all_of(indicator_names),
                       ~ ifelse(is.na(.), NA, as.integer(. + 1))))
```

```{r}
summary(lca_raw[ , indicator_names])
summary(lca_raw$age)
table(lca_raw$gender, useNA = "ifany")
table(lca_raw$degree, useNA = "ifany")
table(lca_raw$race,   useNA = "ifany")
table(lca_raw$wave)
```

# Fit LCA model

**Without covariates**

```{r}
set.seed(687)
f_ind <- cbind(Month, Day, Year, DOW, Scissors, Cactus, President, VP) ~ 1
sub_df <- lca_ready %>% dplyr::sample_frac(0.5)
fit_list <- lapply(2:5, function(k) {
  poLCA(f_ind, data = sub_df, nclass = k, maxiter = 1500, nrep = 3, verbose = FALSE)
})

data.frame(
  k   = 2:5,
  AIC = sapply(fit_list, \(m) m$aic),
  BIC = sapply(fit_list, \(m) m$bic),
  Gsq = sapply(fit_list, \(m) m$Gsq)
)

```

After comparing AIC and BIC and considering simplicity and efficient, we chose 4 classes due to the lowest BIC and a relatively low AIC.

```{r}
set.seed(687)
lca_k4 <- poLCA(f_ind, data = lca_ready, nclass = 4, maxiter = 5000, nrep = 20, verbose = TRUE)
lca_k4$probs
```

```{r}
lca_ready$.rowid <- seq_len(nrow(lca_ready))
mf <- model.frame(f_ind, data = lca_ready, na.action = na.omit)
idx <- as.integer(row.names(mf)) 
tab <- table(lca_k4$predclass, lca_ready$wave[idx])
tab
```

**With covariates**

```{r}
set.seed(687)
f_cov <- cbind(Month, Day, Year, DOW, Scissors, Cactus, President, VP) ~ 
  age + factor(gender) + factor(degree) + factor(race)

lca_cov <- poLCA(f_cov, data = lca_ready, nclass = 4, maxiter = 5000, nrep = 20, verbose = TRUE)

lca_cov$P     
lca_cov$coeff 
```
